[SERVICE]
    Flush                 1
    Log_Level             info
    Daemon                off
    Parsers_File          /fluent-bit/etc/parsers.conf
    storage.path          /var/log/fluent-bit-storage/
    storage.sync          normal
    storage.checksum      off

[INPUT]
    Name                  tail
    Path                  /var/lib/docker/containers/*/*.log
    Parser                docker
    Tag                   docker.*
    DB                    /var/log/fluent-bit-storage/docker.db
    Read_from_Head        true
    Refresh_Interval      5
    Rotate_Wait           30
    Skip_Long_Lines       On
    Mem_Buf_Limit         20MB

[OUTPUT]
    Name                  loki
    Match                 docker.*
    Host                  loki
    Port                  3100
    Labels                job=docker
    Line_Format           json
