[agent]
  interval = "15s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  flush_interval = "15s"
  omit_hostname = true

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  timeout = "5s"
  perdevice_include = ["cpu", "network"]
  total_include = ["cpu", "blkio", "network"]

[[outputs.prometheus_client]]
  listen = ":9273"
  metric_version = 1
